--- #YAML:1.0
name:                HtmlUnit
version:             0.01
abstract:            Java::Inline based wrapper of the HtmlUnit library
license:             ~
author:              
    - awwaiid <awwaiid@thelackthereof.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Inline::Java:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
